layout_spectrum: 0.7400196607428428
typography_spectrum: 0.9638913249517652
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.42659270637834645
  lightness: 0.6165310016311336
  saturation: 0.15475527787129256
  rhythmicContrast: 0.310338678759993
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelscorner
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' Michael''s Corner'
content: []
description: Helping all God's children walk in fulness of life
purpose: []
content_rating:
  adult: false
author:
  name: Michael Sheaver
  email: michael@sheaver.me
github: true
