name: michaelscorner
favicon: null
layout_spectrum: 0.0187826631590724
typography_spectrum: 0.4587636182550341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3666992816142738
  lightness: 0.7131287837401032
  saturation: 0.6455854689702392
  rhythmicContrast: 0.0776286143809557
purpose: []
