layout_spectrum: 0.833249494211361
typography_spectrum: 0.413845129687671
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.08410610264499147
  lightness: 0.11502051719888529
  saturation: 0.4062755247633351
  rhythmicContrast: 0.877859204510817
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelscorner
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' Michael''s Corner'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccec3829-c339-4a89-a0f4-f9e94eec31e6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccec3829-c339-4a89-a0f4-f9e94eec31e6.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Helping all God's children walk in fulness of life
purpose: []
content_rating:
  adult: false
author:
  name: Michael Sheaver
  email: michael@sheaver.me
github: true
