layout_spectrum: 0.833249494211361
typography_spectrum: 0.413845129687671
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.08410610264499147
  lightness: 0.11502051719888529
  saturation: 0.4062755247633351
  rhythmicContrast: 0.877859204510817
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelscorner
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' Michael''s Corner'
content: []
description: Helping all God's children walk in fulness of life
purpose: []
content_rating:
  adult: false
author:
  name: Michael Sheaver
  email: michael@sheaver.me
github: true
